name: DeploySimpleWorkflow
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      RG_LA:
        description: "Resource group name"
        required: true
      LA_NAME:
        description: "Logic App name"
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          dest: ${{ github.run_id }}.zip
          files: ./
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.run_id }}.zip

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - uses: azure/webapps-deploy@v2
        with: 
          app-name: 'test3hd4m-logicapp'
          package: './'
